This notebook generates the umap embeddings of the images in the dataset. The embeddings are saved in a parquet file.

In [1]:
import argparse
import pathlib

import numpy as np
import pandas as pd
import umap

In [ ]:
# set the arg parser
parser = argparse.ArgumentParser(description="UMAP on a matrix")

parser.add_argument("--data_mode", type=str, default="CP", help="data mode to use")

# get the args
args = parser.parse_args()

# set data mode to either "CP" or "scDINO" or "combined" or "terminal"
data_mode = args.data_mode

In [3]:
# set the paths to the data
CP_fs_sc_profiles_path = pathlib.Path(
    "../../data/CP_feature_select/profiles/features_selected_profile.parquet"
).resolve(strict=True)
combined_profiles_path = pathlib.Path(
    "../../data/CP_scDINO_features/combined_CP_scDINO_norm_fs.parquet"
).resolve(strict=True)
scDINO_fs_profiles_path = pathlib.Path(
    "../../data/scDINO/CLS_features_annotated_normalized_feature_selected.parquet"
).resolve(strict=True)

CP_endpoint_profiles_path = pathlib.Path(
    "../../data/CP_feature_select/endpoints/features_selected_profile.parquet"
).resolve(strict=True)

output_path = pathlib.Path("../../data/umap/").resolve()
output_path.mkdir(parents=True, exist_ok=True)

In [4]:
if data_mode == "CP":
    # read the data
    profiles_df = pd.read_parquet(CP_fs_sc_profiles_path)
elif data_mode == "combined":
    # read the data
    profiles_df = pd.read_parquet(combined_profiles_path)
elif data_mode == "scDINO":
    # read the data
    profiles_df = pd.read_parquet(scDINO_fs_profiles_path)
elif data_mode == "terminal":
    # read the data
    profiles_df = pd.read_parquet(CP_endpoint_profiles_path)
else:
    raise ValueError("data_mode must be either 'CP' or 'scDINO' or 'combined'")
print(profiles_df.shape)
# show all columns
pd.set_option("display.max_columns", None)
profiles_df.head()

(17048, 558)

,Metadata_plate,Metadata_Well,Metadata_number_of_singlecells,Metadata_compound,Metadata_dose,Metadata_control,Metadata_ImageNumber,Metadata_FOV,Metadata_Time,Metadata_Cells_Number_Object_Number,Metadata_Cytoplasm_Parent_Cells,Metadata_Cytoplasm_Parent_Nuclei,Metadata_ImageNumber_1,Metadata_ImageNumber_2,Metadata_ImageNumber_3,Metadata_Nuclei_Number_Object_Number,Metadata_Image_FileName_AnnexinV,Metadata_Image_FileName_DNA,Metadata_Image_PathName_AnnexinV,Metadata_Image_PathName_DNA,Metadata_Nuclei_Location_Center_X,Metadata_Nuclei_Location_Center_Y,Metadata_coordinates_x,Metadata_track_id,Metadata_t,Metadata_y,Metadata_x,Metadata_id,Metadata_parent_track_id,Metadata_parent_id,Metadata_coordinates_y,Metadata_distance,Cytoplasm_AreaShape_Area,Metadata_Cytoplasm_AreaShape_BoundingBoxArea,Cytoplasm_AreaShape_Center_Y,Cytoplasm_AreaShape_Compactness,Cytoplasm_AreaShape_Eccentricity,Cytoplasm_AreaShape_Extent,Cytoplasm_AreaShape_FormFactor,Cytoplasm_AreaShape_MajorAxisLength,Cytoplasm_AreaShape_MaximumRadius,Cytoplasm_AreaShape_MinFeretDiameter,Cytoplasm_AreaShape_Orientation,Cytoplasm_AreaShape_Perimeter,Cytoplasm_AreaShape_Solidity,Cytoplasm_AreaShape_Zernike_0_0,Cytoplasm_AreaShape_Zernike_1_1,Cytoplasm_AreaShape_Zernike_2_0,Cytoplasm_AreaShape_Zernike_3_1,Cytoplasm_AreaShape_Zernike_3_3,Cytoplasm_AreaShape_Zernike_5_1,Cytoplasm_AreaShape_Zernike_5_3,Cytoplasm_AreaShape_Zernike_5_5,Cytoplasm_AreaShape_Zernike_6_0,Cytoplasm_AreaShape_Zernike_7_1,Cytoplasm_AreaShape_Zernike_7_3,Cytoplasm_AreaShape_Zernike_7_5,Cytoplasm_AreaShape_Zernike_7_7,Cytoplasm_AreaShape_Zernike_9_1,Cytoplasm_AreaShape_Zernike_9_3,Cytoplasm_AreaShape_Zernike_9_5,Cytoplasm_AreaShape_Zernike_9_7,Cytoplasm_AreaShape_Zernike_9_9,Cytoplasm_Correlation_Correlation_AnnexinV_DNA,Cytoplasm_Correlation_K_AnnexinV_DNA,Cytoplasm_Correlation_K_DNA_AnnexinV,Cytoplasm_Correlation_Manders_AnnexinV_DNA,Cytoplasm_Correlation_Manders_DNA_AnnexinV,Cytoplasm_Correlation_Overlap_AnnexinV_DNA,Cytoplasm_Granularity_1_AnnexinV,Cytoplasm_Granularity_1_DNA,Cytoplasm_Intensity_IntegratedIntensityEdge_DNA,Cytoplasm_Intensity_IntegratedIntensity_AnnexinV,Cytoplasm_Intensity_IntegratedIntensity_DNA,Cytoplasm_Intensity_MADIntensity_AnnexinV,Cytoplasm_Intensity_MassDisplacement_AnnexinV,Cytoplasm_Intensity_MassDisplacement_DNA,Cytoplasm_Intensity_MaxIntensity_AnnexinV,Cytoplasm_Intensity_MaxIntensity_DNA,Cytoplasm_Intensity_MeanIntensityEdge_DNA,Cytoplasm_Intensity_MedianIntensity_AnnexinV,Cytoplasm_Intensity_StdIntensity_AnnexinV,Cytoplasm_Intensity_StdIntensity_DNA,Cytoplasm_Intensity_UpperQuartileIntensity_AnnexinV,Cytoplasm_RadialDistribution_FracAtD_AnnexinV_3of4,Cytoplasm_RadialDistribution_FracAtD_AnnexinV_4of4,Cytoplasm_RadialDistribution_FracAtD_DNA_1of4,Cytoplasm_RadialDistribution_FracAtD_DNA_2of4,Cytoplasm_RadialDistribution_FracAtD_DNA_3of4,Cytoplasm_RadialDistribution_FracAtD_DNA_4of4,Cytoplasm_RadialDistribution_MeanFrac_DNA_1of4,Cytoplasm_RadialDistribution_MeanFrac_DNA_2of4,Cytoplasm_RadialDistribution_MeanFrac_DNA_3of4,Cytoplasm_RadialDistribution_RadialCV_AnnexinV_1of4,Cytoplasm_RadialDistribution_RadialCV_AnnexinV_2of4,Cytoplasm_RadialDistribution_RadialCV_AnnexinV_3of4,Cytoplasm_RadialDistribution_RadialCV_DNA_1of4,Cytoplasm_RadialDistribution_RadialCV_DNA_2of4,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_1_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_2_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_2_2,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_3_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_3_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_4_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_4_2,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_5_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_5_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_6_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_6_2,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_6_4,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_7_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_7_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_7_5,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_8_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_8_2,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_8_4,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_8_6,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_8_8,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_9_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_9_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_9_5,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_9_7,Cytoplasm_RadialDistribution_ZernikeMagnitude_AnnexinV_9_9,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_0_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_1_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_2_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_3_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_4_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_5_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_5_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_6_0,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_7_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_7_5,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_7_7,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_8_6,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_9_1,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_9_3,Cytoplasm_RadialDistribution_ZernikeMagnitude_DNA_9_5,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_1_1,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_2_2,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_3_1,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_3_3,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_4_2,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_4_4,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_5_1,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_5_3,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_5_5,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_6_2,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_6_4,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_6_6,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_7_1,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_7_3,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_7_5,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_7_7,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_8_2,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_8_4,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_8_6,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_8_8,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_9_1,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_9_3,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_9_5,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_9_7,Cytoplasm_RadialDistribution_ZernikePhase_AnnexinV_9_9,Cytoplasm_RadialDistribution_ZernikePhase_DNA_1_1,Cytoplasm_RadialDistribution_ZernikePhase_DNA_2_2,Cytoplasm_RadialDistribution_ZernikePhase_DNA_3_1,Cytoplasm_RadialDistribution_ZernikePhase_DNA_3_3,Cytoplasm_RadialDistribution_ZernikePhase_DNA_4_2,Cytoplasm_RadialDistribution_ZernikePhase_DNA_5_1,Cytoplasm_RadialDistribution_ZernikePhase_DNA_5_3,Cytoplasm_RadialDistribution_ZernikePhase_DNA_5_5,Cytoplasm_RadialDistribution_ZernikePhase_DNA_6_2,Cytoplasm_RadialDistribution_ZernikePhase_DNA_6_4,Cytoplasm_RadialDistribution_ZernikePhase_DNA_6_6,Cytoplasm_RadialDistribution_ZernikePhase_DNA_7_1,Cytoplasm_RadialDistribution_ZernikePhase_DNA_7_3,Cytoplasm_RadialDistribution_ZernikePhase_DNA_7_5,Cytoplasm_RadialDistribution_ZernikePhase_DNA_7_7,Cytoplasm_RadialDistribution_ZernikePhase_DNA_8_2,Cytoplasm_RadialDistribution_ZernikePhase_DNA_8_6,Cytoplasm_RadialDistribution_ZernikePhase_DNA_9_1,Cytoplasm_RadialDistribution_ZernikePhase_DNA_9_3,Cytoplasm_RadialDistribution_ZernikePhase_DNA_9_5,Cytoplasm_RadialDistribution_ZernikePhase_DNA_9_7,Cytoplasm_RadialDistribution_ZernikePhase_DNA_9_9,Cytoplasm_Texture_Correlation_AnnexinV_3_00_256,Cytoplasm_Texture_Correlation_AnnexinV_3_01_256,Cytoplasm_Texture_Correlation_AnnexinV_3_02_256,Cytoplasm_Texture_Correlation_AnnexinV_3_03_256,Cytoplasm_Texture_DifferenceVariance_AnnexinV_3_02_256,Cytoplasm_Texture_InverseDifferenceMoment_AnnexinV_3_00_256,Cytoplasm_Texture_SumAverage_AnnexinV_3_00_256,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,Cells_AreaShape_MaximumRadius,Cells_AreaShape_Orientation,Cells_AreaShape_Solidity,Cells_AreaShape_Zernike_0_0,Cells_AreaShape_Zernike_1_1,Cells_AreaShape_Zernike_2_0,Cells_AreaShape_Zernike_3_1,Cells_AreaShape_Zernike_3_3,Cells_AreaShape_Zernike_4_0,Cells_AreaShape_Zernike_4_2,Cells_AreaShape_Zernike_5_1,Cells_AreaShape_Zernike_5_3,Cells_AreaShape_Zernike_5_5,Cells_AreaShape_Zernike_6_0,Cells_AreaShape_Zernike_6_2,Cells_AreaShape_Zernike_7_1,Cells_AreaShape_Zernike_7_3,Cells_AreaShape_Zernike_7_5,Cells_AreaShape_Zernike_9_1,Cells_AreaShape_Zernike_9_3,Cells_AreaShape_Zernike_9_5,Cells_AreaShape_Zernike_9_7,Cells_Correlation_Correlation_AnnexinV_DNA,Cells_Correlation_K_AnnexinV_DNA,Cells_Correlation_K_DNA_AnnexinV,Cells_Correlation_Manders_AnnexinV_DNA,Cells_Correlation_Manders_DNA_AnnexinV,Cells_Correlation_Overlap_AnnexinV_DNA,Cells_Granularity_1_AnnexinV,Cells_Granularity_1_DNA,Cells_Intensity_IntegratedIntensityEdge_AnnexinV,Cells_Intensity_IntegratedIntensityEdge_DNA,Cells_Intensity_IntegratedIntensity_DNA,Cells_Intensity_MADIntensity_AnnexinV,Cells_Intensity_MassDisplacement_DNA,Cells_Intensity_MaxIntensityEdge_AnnexinV,Cells_Intensity_MaxIntensityEdge_DNA,Cells_Intensity_MeanIntensityEdge_AnnexinV,Cells_Intensity_MeanIntensityEdge_DNA,Cells_Intensity_MeanIntensity_DNA,Cells_Intensity_MedianIntensity_DNA,Cells_Intensity_StdIntensity_DNA,Cells_Intensity_UpperQuartileIntensity_DNA,Cells_Neighbors_AngleBetweenNeighbors_Adjacent,Cells_Neighbors_FirstClosestDistance_Adjacent,Cells_Neighbors_SecondClosestDistance_Adjacent,Cells_RadialDistribution_FracAtD_AnnexinV_3of4,Cells_RadialDistribution_FracAtD_AnnexinV_4of4,Cells_RadialDistribution_FracAtD_DNA_1of4,Cells_RadialDistribution_FracAtD_DNA_4of4,Cells_RadialDistribution_MeanFrac_AnnexinV_3of4,Cells_RadialDistribution_MeanFrac_AnnexinV_4of4,Cells_RadialDistribution_MeanFrac_DNA_1of4,Cells_RadialDistribution_MeanFrac_DNA_2of4,Cells_RadialDistribution_MeanFrac_DNA_3of4,Cells_RadialDistribution_MeanFrac_DNA_4of4,Cells_RadialDistribution_RadialCV_AnnexinV_1of4,Cells_RadialDistribution_RadialCV_AnnexinV_2of4,Cells_RadialDistribution_RadialCV_AnnexinV_3of4,Cells_RadialDistribution_RadialCV_DNA_1of4,Cells_RadialDistribution_RadialCV_DNA_2of4,Cells_RadialDistribution_RadialCV_DNA_3of4,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_1_1,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_2_0,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_2_2,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_3_1,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_3_3,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_4_0,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_4_2,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_5_1,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_5_3,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_5_5,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_6_0,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_6_2,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_6_4,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_7_1,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_7_3,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_7_5,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_8_0,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_8_2,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_8_4,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_8_6,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_8_8,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_9_1,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_9_3,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_9_5,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_9_7,Cells_RadialDistribution_ZernikeMagnitude_AnnexinV_9_9,Cells_RadialDistribution_ZernikeMagnitude_DNA_1_1,Cells_RadialDistribution_ZernikeMagnitude_DNA_2_0,Cells_RadialDistribution_ZernikeMagnitude_DNA_3_1,Cells_RadialDistribution_ZernikeMagnitude_DNA_4_0,Cells_RadialDistribution_ZernikeMagnitude_DNA_4_2,Cells_RadialDistribution_ZernikeMagnitude_DNA_5_1,Cells_RadialDistribution_ZernikeMagnitude_DNA_5_3,Cells_RadialDistribution_ZernikeMagnitude_DNA_6_0,Cells_RadialDistribution_ZernikeMagnitude_DNA_6_2,Cells_RadialDistribution_ZernikeMagnitude_DNA_7_1,Cells_RadialDistribution_ZernikeMagnitude_DNA_7_3,Cells_RadialDistribution_ZernikeMagnitude_DNA_8_0,Cells_RadialDistribution_ZernikeMagnitude_DNA_8_2,Cells_RadialDistribution_ZernikeMagnitude_DNA_8_4,Cells_RadialDistribution_ZernikeMagnitude_DNA_8_8,Cells_RadialDistribution_ZernikeMagnitude_DNA_9_1,Cells_RadialDistribution_ZernikeMagnitude_DNA_9_3,Cells_RadialDistribution_ZernikeMagnitude_DNA_9_5,Cells_RadialDistribution_ZernikeMagnitude_DNA_9_7,Cells_RadialDistribution_ZernikeMagnitude_DNA_9_9,Cells_RadialDistribution_ZernikePhase_AnnexinV_1_1,Cells_RadialDistribution_ZernikePhase_AnnexinV_2_2,Cells_RadialDistribution_ZernikePhase_AnnexinV_3_1,Cells_RadialDistribution_ZernikePhase_AnnexinV_3_3,Cells_RadialDistribution_ZernikePhase_AnnexinV_4_2,Cells_RadialDistribution_ZernikePhase_AnnexinV_4_4,Cells_RadialDistribution_ZernikePhase_AnnexinV_5_1,Cells_RadialDistribution_ZernikePhase_AnnexinV_5_3,Cells_RadialDistribution_ZernikePhase_AnnexinV_5_5,Cells_RadialDistribution_ZernikePhase_AnnexinV_6_2,Cells_RadialDistribution_ZernikePhase_AnnexinV_6_4,Cells_RadialDistribution_ZernikePhase_AnnexinV_6_6,Cells_RadialDistribution_ZernikePhase_AnnexinV_7_1,Cells_RadialDistribution_ZernikePhase_AnnexinV_7_3,Cells_RadialDistribution_ZernikePhase_AnnexinV_7_5,Cells_RadialDistribution_ZernikePhase_AnnexinV_7_7,Cells_RadialDistribution_ZernikePhase_AnnexinV_8_2,Cells_RadialDistribution_ZernikePhase_AnnexinV_8_4,Cells_RadialDistribution_ZernikePhase_AnnexinV_8_6,Cells_RadialDistribution_ZernikePhase_AnnexinV_8_8,Cells_RadialDistribution_ZernikePhase_AnnexinV_9_1,Cells_RadialDistribution_ZernikePhase_AnnexinV_9_3,Cells_RadialDistribution_ZernikePhase_AnnexinV_9_5,Cells_RadialDistribution_ZernikePhase_AnnexinV_9_7,Cells_RadialDistribution_ZernikePhase_AnnexinV_9_9,Cells_RadialDistribution_ZernikePhase_DNA_1_1,Cells_RadialDistribution_ZernikePhase_DNA_2_2,Cells_RadialDistribution_ZernikePhase_DNA_3_1,Cells_RadialDistribution_ZernikePhase_DNA_3_3,Cells_RadialDistribution_ZernikePhase_DNA_4_2,Cells_RadialDistribution_ZernikePhase_DNA_4_4,Cells_RadialDistribution_ZernikePhase_DNA_5_1,Cells_RadialDistribution_ZernikePhase_DNA_5_3,Cells_RadialDistribution_ZernikePhase_DNA_5_5,Cells_RadialDistribution_ZernikePhase_DNA_6_2,Cells_RadialDistribution_ZernikePhase_DNA_6_4,Cells_RadialDistribution_ZernikePhase_DNA_6_6,Cells_RadialDistribution_ZernikePhase_DNA_7_1,Cells_RadialDistribution_ZernikePhase_DNA_7_3,Cells_RadialDistribution_ZernikePhase_DNA_7_5,Cells_RadialDistribution_ZernikePhase_DNA_7_7,Cells_RadialDistribution_ZernikePhase_DNA_8_2,Cells_RadialDistribution_ZernikePhase_DNA_8_4,Cells_RadialDistribution_ZernikePhase_DNA_8_6,Cells_RadialDistribution_ZernikePhase_DNA_8_8,Cells_RadialDistribution_ZernikePhase_DNA_9_1,Cells_RadialDistribution_ZernikePhase_DNA_9_3,Cells_RadialDistribution_ZernikePhase_DNA_9_5,Cells_RadialDistribution_ZernikePhase_DNA_9_7,Cells_RadialDistribution_ZernikePhase_DNA_9_9,Cells_Texture_AngularSecondMoment_DNA_3_02_256,Cells_Texture_Correlation_AnnexinV_3_00_256,Cells_Texture_Correlation_AnnexinV_3_01_256,Cells_Texture_Correlation_AnnexinV_3_02_256,Cells_Texture_Correlation_AnnexinV_3_03_256,Cells_Texture_Correlation_DNA_3_02_256,Cells_Texture_InverseDifferenceMoment_AnnexinV_3_02_256,Cells_Texture_SumAverage_AnnexinV_3_01_256,Cells_Texture_SumAverage_DNA_3_00_256,Nuclei_AreaShape_Compactness,Nuclei_AreaShape_Eccentricity,Nuclei_AreaShape_Extent,Nuclei_AreaShape_FormFactor,Nuclei_AreaShape_MajorAxisLength,Nuclei_AreaShape_MinFeretDiameter,Nuclei_AreaShape_Orientation,Nuclei_AreaShape_Solidity,Nuclei_AreaShape_Zernike_0_0,Nuclei_AreaShape_Zernike_1_1,Nuclei_AreaShape_Zernike_2_0,Nuclei_AreaShape_Zernike_2_2,Nuclei_AreaShape_Zernike_3_1,Nuclei_AreaShape_Zernike_3_3,Nuclei_AreaShape_Zernike_4_0,Nuclei_AreaShape_Zernike_4_2,Nuclei_AreaShape_Zernike_4_4,Nuclei_AreaShape_Zernike_5_1,Nuclei_AreaShape_Zernike_5_3,Nuclei_AreaShape_Zernike_5_5,Nuclei_AreaShape_Zernike_6_0,Nuclei_AreaShape_Zernike_6_2,Nuclei_AreaShape_Zernike_6_4,Nuclei_AreaShape_Zernike_6_6,Nuclei_AreaShape_Zernike_7_1,Nuclei_AreaShape_Zernike_7_3,Nuclei_AreaShape_Zernike_7_5,Nuclei_AreaShape_Zernike_7_7,Nuclei_AreaShape_Zernike_8_0,Nuclei_AreaShape_Zernike_8_2,Nuclei_AreaShape_Zernike_8_4,Nuclei_AreaShape_Zernike_8_6,Nuclei_AreaShape_Zernike_8_8,Nuclei_AreaShape_Zernike_9_1,Nuclei_AreaShape_Zernike_9_3,Nuclei_AreaShape_Zernike_9_5,Nuclei_AreaShape_Zernike_9_7,Nuclei_AreaShape_Zernike_9_9,Nuclei_Correlation_Correlation_AnnexinV_DNA,Nuclei_Correlation_Costes_DNA_AnnexinV,Nuclei_Correlation_K_AnnexinV_DNA,Nuclei_Correlation_K_DNA_AnnexinV,Nuclei_Correlation_Overlap_AnnexinV_DNA,Nuclei_Correlation_RWC_AnnexinV_DNA,Nuclei_Correlation_RWC_DNA_AnnexinV,Nuclei_Granularity_1_DNA,Nuclei_Granularity_2_DNA,Nuclei_Intensity_IntegratedIntensityEdge_AnnexinV,Nuclei_Intensity_IntegratedIntensityEdge_DNA,Nuclei_Intensity_IntegratedIntensity_AnnexinV,Nuclei_Intensity_IntegratedIntensity_DNA,Nuclei_Intensity_LowerQuartileIntensity_AnnexinV,Nuclei_Intensity_LowerQuartileIntensity_DNA,Nuclei_Intensity_MADIntensity_AnnexinV,Nuclei_Intensity_MADIntensity_DNA,Nuclei_Intensity_MassDisplacement_AnnexinV,Nuclei_Intensity_MassDisplacement_DNA,Nuclei_Intensity_MaxIntensityEdge_AnnexinV,Nuclei_Intensity_MaxIntensity_AnnexinV,Nuclei_Intensity_MaxIntensity_DNA,Nuclei_Intensity_MeanIntensityEdge_AnnexinV,Nuclei_Intensity_MeanIntensityEdge_DNA,Nuclei_Intensity_MedianIntensity_DNA,Nuclei_Intensity_StdIntensityEdge_DNA,Nuclei_Neighbors_AngleBetweenNeighbors_Adjacent,Nuclei_Neighbors_FirstClosestDistance_Adjacent,Nuclei_Neighbors_FirstClosestObjectNumber_Adjacent,Nuclei_Neighbors_SecondClosestDistance_Adjacent,Nuclei_RadialDistribution_FracAtD_DNA_1of4,Nuclei_RadialDistribution_FracAtD_DNA_2of4,Nuclei_RadialDistribution_FracAtD_DNA_3of4,Nuclei_RadialDistribution_FracAtD_DNA_4of4,Nuclei_RadialDistribution_MeanFrac_AnnexinV_3of4,Nuclei_RadialDistribution_MeanFrac_AnnexinV_4of4,Nuclei_RadialDistribution_MeanFrac_DNA_1of4,Nuclei_RadialDistribution_MeanFrac_DNA_2of4,Nuclei_RadialDistribution_MeanFrac_DNA_3of4,Nuclei_RadialDistribution_RadialCV_AnnexinV_1of4,Nuclei_RadialDistribution_RadialCV_AnnexinV_2of4,Nuclei_RadialDistribution_RadialCV_AnnexinV_3of4,Nuclei_RadialDistribution_RadialCV_AnnexinV_4of4,Nuclei_RadialDistribution_RadialCV_DNA_1of4,Nuclei_RadialDistribution_RadialCV_DNA_2of4,Nuclei_RadialDistribution_RadialCV_DNA_3of4,Nuclei_RadialDistribution_RadialCV_DNA_4of4,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_1_1,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_2_0,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_2_2,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_3_1,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_3_3,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_4_0,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_4_2,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_5_1,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_5_3,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_5_5,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_6_0,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_6_2,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_6_4,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_7_1,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_7_3,Nuclei_RadialDistribution_ZernikeMagnitude_AnnexinV_7_

In [5]:
# filter the data and drop nan values
print(profiles_df.shape)
# drop nan values in non metadata columns
profiles_df = profiles_df.dropna(
    subset=profiles_df.columns[~profiles_df.columns.str.contains("Meta")]
)
print(profiles_df.shape)

(17048, 558)
(16120, 558)

In [6]:
# get the metadata columns
metadata_cols = profiles_df.columns.str.contains("Metadata_")
metadata_df = profiles_df.loc[:, metadata_cols]
features_df = profiles_df.loc[:, ~metadata_cols]

# set the umap parameters
umap = umap.UMAP(
    n_neighbors=15,
    n_components=2,
    metric="euclidean",
    random_state=42,
    min_dist=0.1,
    n_epochs=500,
    learning_rate=1,
)

# fit the umap model
umap.fit(features_df)

# transform the data
umap_transformed = umap.transform(features_df)

# create a dataframe with the transformed data
umap_df = pd.DataFrame(
    umap_transformed, columns=["UMAP0", "UMAP1"], index=features_df.index
)

# combine the metadata and umap dataframes
umap_df = pd.concat([metadata_df, umap_df], axis=1)
print(umap_df.shape)
umap_df.head()

/home/lippincm/miniforge3/envs/timelapse_analysis_env/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/lippincm/miniforge3/envs/timelapse_analysis_env/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

(16120, 35)

/home/lippincm/miniforge3/envs/timelapse_analysis_env/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

,Metadata_plate,Metadata_Well,Metadata_number_of_singlecells,Metadata_compound,Metadata_dose,Metadata_control,Metadata_ImageNumber,Metadata_FOV,Metadata_Time,Metadata_Cells_Number_Object_Number,Metadata_Cytoplasm_Parent_Cells,Metadata_Cytoplasm_Parent_Nuclei,Metadata_ImageNumber_1,Metadata_ImageNumber_2,Metadata_ImageNumber_3,Metadata_Nuclei_Number_Object_Number,Metadata_Image_FileName_AnnexinV,Metadata_Image_FileName_DNA,Metadata_Image_PathName_AnnexinV,Metadata_Image_PathName_DNA,Metadata_Nuclei_Location_Center_X,Metadata_Nuclei_Location_Center_Y,Metadata_coordinates_x,Metadata_track_id,Metadata_t,Metadata_y,Metadata_x,Metadata_id,Metadata_parent_track_id,Metadata_parent_id,Metadata_coordinates_y,Metadata_distance,Metadata_Cytoplasm_AreaShape_BoundingBoxArea,UMAP0,UMAP1
0,1,C-10,173,Staurosporine,78.13,test,1,0003,13.0,2.0,2,1,1,1.0,1.0,1.0,C-10_F0003_T0014_Z0001_C05_illumcorrect_aligne...,C-10_F0003_T0014_Z0001_C01_illumcorrect_aligne...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,22.545169,487.346426,"[22.545168892380204, 487.3464257659073]",177,13.0,487.0,23.0,14000039.0,-1,13000037.0,"[23.0, 487.0]",0.571736,-1.385279,8.549203,-2.187669
1,1,C-10,173,Staurosporine,78.13,test,1,0003,13.0,12.0,12,10,1,1.0,1.0,10.0,C-10_F0003_T0014_Z0001_C05_illumcorrect_aligne...,C-10_F0003_T0014_Z0001_C01_illumcorrect_aligne...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,70.834281,1604.187652,"[70.83428107229895, 1604.187652315191]",111,13.0,1604.0,71.0,14000155.0,-1,13000145.0,"[71.0, 1604.0]",0.250352,-0.951782,8.580102,-1.879205
2,1,C-10,173,Staurosporine,78.13,test,1,0003,13.0,14.0,14,12,1,1.0,1.0,12.0,C-10_F0003_T0014_Z0001_C05_illumcorrect_aligne...,C-10_F0003_T0014_Z0001_C01_illumcorrect_aligne...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,78.445255,1054.451095,"[78.44525547445255, 1054.451094890511]",53,13.0,1054.0,78.0,14000083.0,-1,13000075.0,"[78.0, 1054.0]",0.633829,-0.771676,6.715151,0.346174
3,1,C-10,173,Staurosporine,78.13,test,1,0003,13.0,19.0,19,15,1,1.0,1.0,15.0,C-10_F0003_T0014_Z0001_C05_illumcorrect_aligne...,C-10_F0003_T0014_Z0001_C01_illumcorrect_aligne...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,109.247411,459.294591,"[109.24741081703107, 459.2945914844649]",19,13.0,459.0,109.0,14000036.0,-1,13000031.0,"[109.0, 459.0]",0.384703,-1.258782,9.229943,-1.038720
4,1,C-10,173,Staurosporine,78.13,test,1,0003,13.0,23.0,23,17,1,1.0,1.0,17.0,C-10_F0003_T0014_Z0001_C05_illumcorrect_aligne...,C-10_F0003_T0014_Z0001_C01_illumcorrect_aligne...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,/home/lippincm/4TB_A/live_cell_timelapse_apopt...,133.526082,1462.371809,"[133.5260821309656, 1462.371809100999]",180,13.0,1462.0,134.0,14000127.0,-1,13000123.0,"[134.0, 1462.0]",0.602362,-0.801914,9.386768,0.594258

In [7]:
# save the umap dataframe
umap_df.to_parquet(f"../../data/umap/{data_mode}_umap_transformed.parquet")